In [8]:
from pathlib import Path

import pandas as pd
import numpy as np

In [9]:
geoinfo_dir = Path('/home/gabriel-david/Estudo/Mestrado/cienciadados/geoinfo-papers/2013')

In [11]:
artigos = pd.read_csv(
    geoinfo_dir / 'artigos.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Artigos: {len(artigos)} registros")

pessoas = pd.read_csv(
    geoinfo_dir / 'pessoas.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Pessoas: {len(pessoas)} registros")

autoria = pd.read_csv(
    geoinfo_dir / 'autoria.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Autoria: {len(autoria)} registros")

comite = pd.read_csv(
    geoinfo_dir / 'comite_cientifico.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Comitê: {len(comite)} registros")

organizacao = pd.read_csv(
    geoinfo_dir / 'organização.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Organização: {len(organizacao)} registros")

evento = pd.read_csv(
    geoinfo_dir / 'evento.csv',
    quotechar='"',
    quoting=1,
    encoding='utf-8-sig'
)
print(f"Evento: {len(evento)} registros")

Artigos: 18 registros
Pessoas: 102 registros
Autoria: 52 registros
Comitê: 110 registros
Organização: 5 registros
Evento: 1 registros

In [12]:
artigos.head()

,id_artigo,titulo,abstract,n_paginas,tipo_artigo,lingua,n_edicao
0,1,Georeferencing facts in road networks,Information about a location can be imprecise ...,8,full,english,13
1,2,A conceptual model for representation of taxi ...,The large-scale capture of data about the moti...,12,full,english,13
2,3,Estatãstica de varredura unidimensional para d...,This paper presents a new approach for cluster...,6,full,portuguese,13
3,4,Um framework para recuperaãão semãntica de dad...,Geographic data represent objects for which th...,6,full,portuguese,13
4,5,A conceptual analysis of resolution,The literature in geographic information scien...,12,full,english,13

In [13]:
pessoas.head()

,id_pessoa,nome,instituicao
0,1,Fãbio da Costa Albuquerque,Pontifãcia Universidade Catãlica do Rio de Jan...
1,2,Ivanildo Barbosa,Pontifãcia Universidade Catãlica do Rio de Jan...
2,3,Marco Antonio Casanova,Pontifãcia Universidade Catãlica do Rio de Jan...
3,4,Marcelo Tãlio Monteiro de Carvalho,Pontifãcia Universidade Catãlica do Rio de Jan...
4,5,Ana Maria Amorim,UNIFACS

In [14]:
autoria.head()

   id_autoria  id_artigo  id_pessoa  ordem_autoria  autor_correspondente
0           1          1          1              1                 False
1           2          1          2              2                 False
2           3          1          3              3                 False
3           4          1          4              4                 False
4           5          2          5              1                 False

In [15]:
comite.head()

   id_revisor  id_pessoa  n_edicao
0           1         54        13
1           2         55        13
2           3          3        13
3           4         56        13
4           5         57        13

In [16]:
organizacao.head()

   id_organizador  id_pessoa              funcao  n_edicao
0               1         49       General Chair        13
1               2         50       Program Chair        13
2               3         51  Local Organization        13
3               4         52  Local Organization        13
4               5         53  Local Organization        13

In [17]:
evento.head()

   id_evento  n_edicao   ano             local
0          1        13  2013  Campos do Jordão

In [18]:
#DF Papers
df = artigos.merge(autoria, on='id_artigo')
df = df.merge(pessoas[['id_pessoa', 'nome', 'instituicao']], on='id_pessoa')

df_papers = df.groupby('id_artigo').agg({
    'titulo': 'first',
    'abstract': 'first',
    'tipo_artigo': 'first',
    'lingua': 'first',
    'n_edicao': 'first',
    'nome': list,
    'instituicao': list
}).reset_index()
df_papers

,id_artigo,titulo,abstract,tipo_artigo,lingua,n_edicao,nome,instituicao
0,1,Georeferencing facts in road networks,Information about a location can be imprecise ...,full,english,13,"[Fãbio da Costa Albuquerque, Ivanildo Barbosa,...",[Pontifãcia Universidade Catãlica do Rio de Ja...
1,2,A conceptual model for representation of taxi ...,The large-scale capture of data about the moti...,full,english,13,"[Ana Maria Amorim, Jorge Campos]","[UNIFACS, UNIFACS]"
2,3,Estatãstica de varredura unidimensional para d...,This paper presents a new approach for cluster...,full,portuguese,13,"[Marcelo Azevedo Costa, Marcos Oliveira Prates...","[Universidade Federal de Minas Gerais (UFMG), ..."
3,4,Um framework para recuperaãão semãntica de dad...,Geographic data represent objects for which th...,full,portuguese,13,"[Jaudete Daltio, Carlos Alberto de Carvalho]","[Universidade Estadual de Campinas (UNICAMP), ..."
4,5,A conceptual analysis of resolution,The literature in geographic information scien...,full,english,13,"[Auriol Degbelo, Werner Kuhn]","[University of Muenster, University of Muenster]"
5,6,Ontology-based geographic data access in a pee...,Ontology-Based Data Access (OBDA) is the probl...,full,english,13,"[Rafael Figueiredo, Daniela Pitta, Ana Carolin...","[Universidade Federal de Pernambuco (UFPE), Un..."
6,7,Distributed vector based spatial data conflati...,Spatial data conflation is a key task for cons...,full,english,13,"[Sãrgio Freitas, Ana Paula Afonso]","[Universidade de Lisboa, Universidade de Lisboa]"
7,8,GeoSQL: um ambiente online para aprendizado de...,The standardization of the Structured Query La...,short,portuguese,13,"[Anderson L. S. Freitas, Clodoveu A. Davis Jun...","[Universidade Federal de Minas Gerais (UFMG), ..."
8,9,M-Attract: assessing the attractiveness of pla...,Attractiveness of places has been studied by s...,full,english,13,"[Andre Salvaro Furtado, Renato Fileto, Chiara ...",[Universidade Federal de Santa Catarina (UFSC)...
9,10,Determinação da rede de drenagem em grandes ...,The drainage network computation is not a triv...,short,portuguese,13,"[Thiago L. Gomes, Magalhã, Salles V. G. es, M...","[Universidade Federal de Viãosa (UFV), Univers..."
10,11,Data quality in agriculture applications,Data quality is a common concern in a wide ran...,full,english,13,"[Joana E. Gonzales Malaverri, Claudia Bauzer M...","[Universidade de Campinas (UNICAMP), Universid..."
11,12,Geocodificaãão de endereãos urbanos com indica...,Urban addresses are one of the most important ...,short,portuguese,13,"[Douglas Martins, Clodoveu A. Davis Junior, Fr...","[Universidade Federal de Minas Gerais (UFMG), ..."
12,13,Expansão do conteãdo de um gazetteer: nomes hi...,The efficiency of a geographic database is dir...,short,portuguese,13,"[Tiago Henrique V. M. Moura, Clodoveu A. Davis...","[Universidade Federal de Minas Gerais (UFMG), ..."
13,14,"GeoSTAT ã a system for visualization, analysis...","Nowadays, there is a considerable amount of sp...",full,english,13,"[Maxwell Guimarães de Oliveira, Clãudio de Sou...",[Universidade Federal de Campina Grande (UFCG)...
14,15,TerraME observer: an extensible real-time visu...,This paper presents ongoing research results o...,full,english,13,"[Antonio Jose C Rodrigues, Tiago G. S. Carneir...","[Universidade Federal de Ouro Preto (UFOP), Un..."
15,16,Proposta de infraestrutura para a gestão de c...,This work discuss how the area of e-Science ha...,short,portuguese,13,"[Alaor Bianco Rodrigues, Walter Abrahão Dos Sa...",[Instituto Nacional de Pesquisas Espaciais (IN...
16,17,Challenges of the anthropocene epoch ã support...,Work on multiscale issues presents countless c...,full,english,13,"[Andre Santanche, Claudia Bauzer Medeiros, Gen...","[Universidade de Campinas (UNICAMP), Universid..."
17,18,Acessibilidade em mapas urbanos para portadore...,Um dos Grandes Desafios para a Computaãão bras...,short,portuguese,13,"[Simone I. R. Xavier, Clodoveu A. Davis Junior]","[Universidade Federal de Minas Gerais (UFMG), ..."

In [19]:
#DF Comitê
df_comite = comite.merge(pessoas, on='id_pessoa')
df_comite = df_comite[['id_pessoa', 'nome', 'instituicao', 'n_edicao']]
df_comite = df_comite.sort_values('nome').reset_index(drop=True)
df_comite

,id_pessoa,nome,instituicao,n_edicao
0,19,Ana Paula Afonso,Universidade de Lisboa,13
1,19,Ana Paula Afonso,Universidade de Lisboa,13
2,95,Andrea Iabrudi,Universidade Federal de Ouro Preto,13
3,95,Andrea Iabrudi,Universidade Federal de Ouro Preto,13
4,81,Angela Schwering,ifgi,13
...,...,...,...,...
105,59,Val´ eria Times,UFPE,13
106,50,Vania Bogorny,"Federal University of Santa Catarina, UFSC",13
107,50,Vania Bogorny,"Federal University of Santa Catarina, UFSC",13
108,13,Werner Kuhn,University of Muenster,13
109,13,Werner Kuhn,University of Muenster,13